# Generated by Django 5.2.8 on 2026-04-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField()),
                ('total_customers', models.IntegerField()),
                ('date_range_start', models.DateTimeField(blank=True, null=True)),
                ('date_range_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_customers', models.IntegerField()),
                ('active_customers', models.IntegerField()),
                ('avg_monetary', models.FloatField()),
                ('total_revenue', models.FloatField()),
                ('vip_count', models.IntegerField(default=0)),
                ('regular_count', models.IntegerField(default=0)),
                ('at_risk_count', models.IntegerField(default=0)),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.uploadeddataset')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('recency', models.IntegerField(help_text='Days since last purchase')),
                ('frequency', models.IntegerField(help_text='Number of distinct orders')),
                ('monetary', models.FloatField(help_text='Total revenue from customer')),
                ('cluster', models.IntegerField(help_text='Cluster number (0, 1, 2)')),
                ('segment', models.CharField(help_text='VIP, Regular, or At Risk', max_length=50)),
                ('pc1', models.FloatField(help_text='First principal component')),
                ('pc2', models.FloatField(help_text='Second principal component')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.uploadeddataset')),
            ],
            options={
                'ordering': ['-monetary'],
                'indexes': [models.Index(fields=['customer_id'], name='api_custome_custome_d943d0_idx'), models.Index(fields=['segment'], name='api_custome_segment_46733e_idx'), models.Index(fields=['dataset'], name='api_custome_dataset_d685ee_idx')],
            },
        ),
    ]
